import pandas as pd
import os
import argparse

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--lr", type=str, default="1e-4")
    parser.add_argument("--seed", type=str, default="42")
    parser.add_argument("--emb_version", type=str, default="v8")
    parser.add_argument("--sampling", type=str, default="100pct")
    parser.add_argument("--data_type", type=str, default="original")
    return parser.parse_args()

if __name__ == "__main__":
    args = parse_args()

    dfs = []
    missing_files = []

    print("Hunting for exact length submission files...")
    
    # Explicitly loop through the exact sequence lengths (13 down to 1)
    for seq in range(13, 0, -1):
        # 1. Construct the exact directory name generated by amex_train.py
        dir_name = f"S3_student_{args.data_type}_{args.emb_version}_{seq}_{args.sampling}_{args.lr}_{args.seed}"
        
        # 2. Construct the exact file name (matching your dynamic naming logic)
        file_name = 'submission.csv.zip'
            
        # 3. Build the full path
        file_path = f"./logs/Amex/{dir_name}/{file_name}"
        
        # 4. Rigorously check for its existence
        if os.path.exists(file_path):
            print(f"[{seq}/13] Found: {file_path}")
            dfs.append(pd.read_csv(file_path))
        else:
            missing_files.append(file_path)

    # Hard-Fail Safety Check
    if missing_files:
        print("\n[ERROR] The following expected files are missing:")
        for mf in missing_files:
            print(f" - {mf}")
        print("\nMerge aborted! This prevents you from submitting an incomplete file to Kaggle.")
        print("Please check your training logs to see which exact-length run failed.")
        exit(1)

    print("\nAll 13 files located safely. Initiating merge...")

    # Stack all mutually exclusive predictions on top of each other
    final_df = pd.concat(dfs, ignore_index=True)

    # Sort alphabetically by customer_ID (Kaggle evaluates based on this sorting)
    final_df = final_df.sort_values('customer_ID')

    output_path = f"./logs/Amex/S3_student_{args.data_type}_{args.emb_version}_AllMerged_{args.sampling}_{args.lr}_{args.seed}/"
    if not os.path.exists(output_path):
        os.makedirs(output_path)
    final_df.to_csv(f'{output_path}/submission.csv.zip', index=False, compression='zip')

    print(f"\n✅ Successfully merged {len(final_df)} rows! (Expected around 924,621)")
    print(f"✅ Saved final submission to: {output_path}")
   
    print("Submitting...")
    submit_message = 'test ensemble thin'
    os.system(
                f"""kaggle competitions submit -c amex-default-prediction -f {output_path}/submission.csv.zip -m '{submit_message}'"""
            )

